### ISSUE TITLE
Existing Api Test

### ISSUE THREAD

**Issue by paulkagiri** [sleberknight/sparkjava-testing#1]
I have gone through the READMe and also some [articles](http://www.fortitudetec.com/blogs/2016/12/05/testing-http-clients-using-the-spark-micro-framework) you've written like but I can't seem to figure out whether the tests work in isolation/independently. I mean when you say
```java
@ClassRule
public static final SparkServerRule SPARK_SERVER = new SparkServerRule(http -> {
    http.get("/ping", (request, response) -> "pong");
    http.get("/health", (request, response) -> "healthy");
});
```
do you mean that is what one should have as their Api? I mean that would be a tightly coupled scenario

**Comment by sleberknight** [comment]
Hi Paul, I obviously missed this and you've probably moved along. But I thought I'd reply anyway, especially since I just merged a pull request that @pfichtner nicely submitted this past March to update the code to JUnit Jupiter.

Anyway, if I understand your question, this library was originally something I used for a little while to specifically test _HTTP client_ code. The use case was a third-party web service that did not have any kind of test system, only production. But we still wanted to test that our client code did what it was supposed to do. So, this allowed us to simulate that third-party API and at least verify the basics of our client code.

Since then we've stopped using Spark and instead use the testing support in Dropwizard (since our services are also using Dropwizard). Dropwizard has various JUnit Jupiter extensions.
